### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by alexcb** [glehmann/tree-sitter-earthfile#10]
Highlighting fails at the "mocks" target when viewing https://github.com/earthly/earthly/blob/main/Earthfile

I was able to simplify the Earthfile to:

```
VERSION 0.8
FROM alpine

mocks:
    FOR f IN $(find / -name 'somefile')
		RUN echo "found $f"
    END

other-target:
    RUN --secret GH_TOKEN=a-b-c --mount=type=secret,id=myid,mode=0400,target=/root/.ssh/id_rsa ssh-add -l
```

which has an error when trying to highlight the FOR line:

![image](https://github.com/glehmann/tree-sitter-earthfile/assets/1806823/9b51dd1b-5980-4de6-a45e-47879d62866b)

Note that when the other-target's RUN is removed (or simplified), highlighting works.

**Comment by glehmann** [comment]
I haven’t implemented the form `--secret <env-var>=<secret-id>`, only `--secret <secret-id>`.

I’m fixing it

**Comment by glehmann** [comment]
I have no idea why the error propagates that far though :-/
